In [139]:
import pandas as pd
import numpy as np

# ---------- 1. Load full WIOD file ----------
df = pd.read_stata("WIOT2014_October16_ROW.dta")
df = df.drop(columns=["IndustryCode", "IndustryDescription", "Year", "RNr"])

In [140]:
df = df.groupby("Country").sum().reset_index()
df2 = df['Country'].copy().to_frame()

In [141]:
for count in df['Country']:
    newCol = count
    df2.loc[:,newCol] = df[[col for col in df.columns if col.startswith("v" + count)]].sum(axis=1)
df2 = df2.drop(columns=['TOT'])
df2 = df2[df2['Country'] != 'TOT']

In [144]:
df3 = df2.iloc[:,~(df2.columns.isin(['USA','CHN','CAN','MEX']))]
df4 = df3['Country'].copy().to_frame()
df4['ROW'] = np.sum(df3.iloc[:,1:],axis = 1)
df5 = df.merge(df2.loc[:,['CAN','CHN','MEX','USA']],df4,on=['Country'])
df5

ValueError: The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

In [ ]:


df4[['CAN','CHN','MEX','USA']]=df2[['vCAN','vCHN','vMEX','vUSA']]
df5 = df4[df4['Country'].isin(['CAN','CHN','MEX','USA','ROW'])]
df5

In [137]:
df6 = df4[~df4['Country'].isin(['CAN','CHN','MEX','USA'])]
df6 = df6.iloc[:,1:].sum(axis=0)
df6

ROW    8.943072e+07
CAN    1.833062e+05
CHN    1.705575e+06
MEX    1.362984e+05
USA    1.442509e+06
dtype: float64

In [138]:
df5.loc[df5['Country']=='ROW'].iloc[:,1:]=df6.T
df5

C:\Users\2025\AppData\Local\Temp\ipykernel_28048\3606179397.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df5.loc[df5['Country']=='ROW'].iloc[:,1:]=df6.T

,Country,ROW,CAN,CHN,MEX,USA
5,CAN,1.869769e+05,2.688664e+06,1.781529e+04,8.237104e+03,3.504821e+05
7,CHN,1.990187e+06,4.963617e+04,2.931964e+07,3.832965e+04,3.473111e+05
29,MEX,7.366730e+04,1.975722e+04,7.395224e+03,1.762304e+06,2.673655e+05
36,ROW,2.412811e+07,6.463313e+04,8.041709e+05,4.374744e+04,5.695728e+05
44,USA,1.344523e+06,2.919298e+05,1.120514e+05,1.785871e+05,2.904393e+07

In [ ]:
e = 5.0

l2014 = np.array([[0.923, 0.011,0.009,0.011,0.046],
                [0.004,0.941,0.0000001,0.001,0.055],
                [0.084,0.018,0.830,0.004,0.064],
                [0.090,0.015,0.006,0.832,0.057]])
l2000 = np.array([[0.932, 0.003,0.007,0.012,0.046],
                [0.004,0.931,0.0000001,0.001,0.064],
                [0.097,0.002,0.845,0.003,0.054],
                [0.114,0.004,0.005,0.816,0.061]])

t7 = np.full(shape=(4,6),fill_value=np.nan)

for i in range(0,4):
    arr = np.concatenate([np.arange(0, i), np.arange(i + 1, 5)])
    t7[i,0] = 1/e*np.sum(l2000[i,arr]/l2000[i,i]*(l2014[i,arr]-l2000[i,arr])/l2000[i,arr])

for i in range(0,4):
    for j in range(0,5):
            if j == i:
                 continue
            t7[i,j+1] = 1/e*l2000[i,j]/l2000[i,i]*(l2014[i,j]-l2000[i,j])/l2000[i,j]/t7[i,0]

df7 = pd.DataFrame(t7,columns=['GFT','US Cont','CHN Cont','MEX Cont','CAN Cont','ROW Cont'])
df7

        GFT   US Cont  CHN Cont  MEX Cont  CAN Cont  ROW Cont
0  0.001931       NaN  0.888889  0.222222 -0.111111  0.000000
1 -0.001933 -0.000000       NaN -0.000000 -0.000000  1.000000
2  0.003314 -0.928571  1.142857       NaN  0.071429  0.714286
3 -0.003922  1.500000 -0.687500 -0.062500       NaN  0.250000